FROM php:7.4-fpm-alpine

# install extension for db connection
RUN docker-php-ext-install pdo_mysql

COPY --from=composer /usr/bin/composer /usr/bin/composer

USER 1000:1000
WORKDIR /var/www
CMD composer install; php-fpm 
EXPOSE 9000